name: Unit Tests UI
run-name: Unit Tests UI - ${{ github.run_id }} - @${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'web/**'
  merge_group:
    paths:
      - 'web/**'

jobs:
  test:
    name: Test UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v3

      - name: Setup Node Toolchain
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test
